apiVersion: v1
kind: ResourceQuota
metadata:
  name: accounting-quota
  namespace: accounting-platform
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "5"
    services: "20"
    pods: "50"
